### ISSUE TITLE
Provide URL to image of filtered topology

### ISSUE THREAD

**Issue by ekrichbaum** [netbox-community/netbox-topology-views#172]
API return of image.  Similar to the api in core for rack face elevations. Potentially using a saved filter or a given set of parameters.

```
api/dcim/racks/{id}/elevation/?face=front&render=svg&unit_width=220&unit_height=22&legend_width=30&expand_devices=true&include_images=true
```

This would allow for topology diagram to be included in other views or projects.

**Comment by dreng** [comment]
While I like your idea, I currently don't see a way to implement it.

We use vis.js which doesn't provide image exports nor API calls. Our current implemented PNG export feature uses the trick that a user can click a button to export the current canvas. Both vis.js and the export feature need Javascript. We collect all needed data and pass it to vis.js which then renders the canvas. Since Javascript runs on a client, we are unable to render a canvas on the NetBox server and pass the result as an API response.

The rack SVG export is a total different story. Everything can me calculated and rendered using pure python which runs on the server. That's basically what we do with our XML export feature. Therefore you are able to export to XML by API call, which unfortunately doesn't help here.

Coorect me if I'm wrong but I don't see a chance to implement this feature.
