### ISSUE TITLE
Server Error after adding an Object Count Widget

### ISSUE THREAD

**Issue by maxzapp** [netbox-community/netbox-topology-views#303]
### NetBox version

3.5.1

### Topology Views version

3.5.0

### Steps to Reproduce

1 create new widget object count
2 add  a topology view model

### Expected Behavior

A new widget will be generated

### Observed Behavior

Server Error occours:
Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:
<class 'AttributeError'>
'Manager' object has no attribute 'restrict'

Python version: 3.8.10
NetBox version: 3.5.1
If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by dreng** [comment]
Hi @maxzapp,

I am not able to reproduce this bug as there's no "topology view object". What I see is this:

![image](https://github.com/mattieserver/netbox-topology-views/assets/20901110/d8b00089-4001-4113-9a71-d2a467bd452a)

Both of these models do anything, just because it makes no sense at all to expect an object list for this models. But both of them don't give me a server error.

**Comment by maxzapp** [comment]
Hi, i corrected my description . These modes maybe make no sense but while explorung the new dasboard i added them an run into this error.

**Comment by maxzapp** [comment]
Hi

its in object count not in list

br
Am 15. Mai 2023, 21:35 +0200 schrieb Mario ***@***.***>:

**Comment by dreng** [comment]
I can reproduce it now. You could have added to your observed behaviour that you lock yourself out of NetBox when you reproduce the error. For all those who have locked themselves out:
- **Start your venv:** source /opt/netbox/venv/bin/activate
- **Start DB Shell:** python3 /opt/netbox/netbox/manage.py dbshell
- **Find User IDs with problematic data:** select user_id from extras_dashboard where config::text like '%topology%';
- **Delete entry:** delete from extras_dashboard where user_id=<USER_ID>;

But the question is what we can do about it. These models are not intended to be listed nor counted. I think it is a stupid solution to add more view classes just to catch an error that should not occur. There should be an option that can be added to models so that the model will not be listed in the dashboard config. If that's the case already, please provide relevant information. If not, the bug should be addressed upstream in my opinion.

**Comment by dreng** [comment]
Never mind, nothing bad happened. Your solution is shorter and better of course.

**Comment by dreng** [comment]
I asked at https://github.com/netbox-community/netbox/discussions/12520#discussioncomment-5930293 two weeks ago about adding a parameter to the model in order to tell NetBox to not list NTV in the dashboard config. Unfortunately there hasn't been any reply. I mark this as 'pending closure' since there's nothing we can do about the current behavior, especially not without help from the NetBox Team.

**Comment by dreng** [comment]
As a last resort I opened a feature request in order to be able to hide the problematic models from the widget configuration. See https://github.com/netbox-community/netbox/issues/12810
